timezone: Europe/London
markdown: rdiscount
permalink: /:year/:month/:day/:title.html
exclude: ["bower.json", "node_modules", "Gruntfile.js", "package.json", "README.md", 'bower_components', 'build', 'vagrant']
