timezone: Europe/London
paginate: 1
markdown: rdiscount
permalink: /:year/:month/:day/:title.html
exclude: ["bower.json", "node_modules", "Gruntfile.js", "package.json", "README.md", 'bower_components', 'build', 'vagrant']
excerpt_separator: <!--more-->
collections:
    islam:
        output: true
