timezone: Europe/London
paginate: 20
markdown: kramdown
permalink: /:year/:month/:day/:title.html
exclude: ["node_modules", "gulpfile.js", "package.json", "README.md", "build", "CNAME"]
excerpt_separator: <!--more-->
base_url: "http://ssst.co"
collections:
    islam:
        output: true
gems:
   - jekyll-paginate
